api-version: '1.21.11'
name: EggSplosion
version: '5.1'
main: com.g0ldensp00n.eggsplosion.EggSplosion
description: My first Bukkit plugin with Gradle
commands:
    lobby:
        description: Join a lobby
        usage: /lobby <join|create|list> <lobbyName>
    map:
        description: Create and Edit Maps
        usage: /map <tools>
    weapon:
        description: Weapon Commands
        usage: /weapon

